import { XMR_ADDRESS_RE } from "./constants.js";
import { encodeUrlPart } from "./format.js";

export function isXmrAddress(value) {
  return XMR_ADDRESS_RE.test(String(value ?? "").trim());
}

export function parseRoute(hash = "") {
  const raw = hash.startsWith("#") ? hash.slice(1) : hash;
  const [pathRaw, queryRaw = ""] = raw.split("?");
  const path = pathRaw.startsWith("/") ? pathRaw : `/${pathRaw}`;
  // Hash query keys are route-local and intentionally short to reduce the raw
  // JS/HTML generated by every control link: p/s for page/size, w/m for graph
  // window/mode, wallet c/s/d/e/x for worker view/sort/dir/dead/details, setup
  // a/o/p/g/al/h/u for address/os/profile/gpu/algo/hashrate/unit.
  const query = Object.fromEntries(new URLSearchParams(queryRaw));
  const parts = path.split("/").filter(Boolean).map(decodeURIComponent);
  // Route objects are private app state: n name, p canonical hash path, q query,
  // a wallet address, t wallet tab, c block coin/port.
  if (!parts.length) return { n: "home", p: "#/", q: query };
  if (parts[0] === "wallet") {
    const tab = parts[2] || "overview";
    if (!isWalletTab(tab)) return { n: "home", p: "#/", q: query };
    return {
      n: "wallet",
      a: parts[1] || "",
      t: tab,
      p: `#/wallet/${encodeUrlPart(parts[1] || "")}/${tab}`,
      q: query
    };
  }
  if (parts[0] === "blocks" && parts[1]) {
    const coin = coinPortFromRoute(parts[1]);
    if (!coin) return { n: "blocks", p: "#/blocks", q: query };
    return { n: "blocks", c: coin, p: `#/blocks/${encodeUrlPart(routeCoinId(coin))}`, q: query };
  }
  if (["coins", "blocks", "payments", "calc", "setup", "help"].includes(parts[0])) return { n: parts[0], p: `#/${parts[0]}`, q: query };
  return { n: "home", p: "#/", q: query };
}

export function walletRoute(address, tab = "overview") {
  return `#/wallet/${encodeUrlPart(address)}/${encodeUrlPart(walletTab(tab))}`;
}

function walletTab(value) {
  return isWalletTab(value) ? value : "overview";
}

function isWalletTab(value) {
  return ["overview", "block-rewards", "withdrawals", "payment-threshold", "email-alerts"].includes(value);
}

function coinPortFromRoute(value) {
  const text = String(value ?? "");
  return /^\d+$/.test(text) ? text : "";
}

export function routeCoinId(port) {
  return String(port);
}
